# Generated by Django 4.2.3 on 2023-07-07 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('starting_time', models.TimeField()),
                ('ending_time', models.TimeField()),
                ('time_slot_duration', models.PositiveIntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('specialization', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('phone_no', models.CharField(max_length=20)),
                ('doctor_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='doctor_app.doctorinfo')),
            ],
        ),
    ]
