# Generated by Django 4.2.3 on 2023-07-05 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
