# Generated by Django 4.2.3 on 2023-07-10 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('disease', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=20)),
                ('state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh (Amaravati)'), ('Arunachal Pradesh', 'Arunachal Pradesh (Itanagar)'), ('Assam', 'Assam (Dispur)'), ('Bihar', 'Bihar (Patna)'), ('Chhattisgarh', 'Chhattisgarh (Raipur)'), ('Goa', 'Goa (Panaji)'), ('Gujarat', 'Gujarat (Gandhinagar)'), ('Haryana', 'Haryana (Chandigarh)'), ('Himachal Pradesh', 'Himachal Pradesh (Shimla)'), ('Jharkhand', 'Jharkhand (Ranchi)'), ('Karnataka', 'Karnataka (Bangalore)'), ('Kerala', 'Kerala (Thiruvananthapuram)'), ('Madhya Pradesh', 'Madhya Pradesh (Bhopal)'), ('Maharashtra', 'Maharashtra (Mumbai)'), ('Manipur', 'Manipur (Imphal)'), ('Meghalaya', 'Meghalaya (Shillong)'), ('Mizoram', 'Mizoram (Aizawl)'), ('Nagaland', 'Nagaland (Kohima)'), ('Odisha', 'Odisha (Bhubaneshwar)'), ('Punjab', 'Punjab (Chandigarh)'), ('Rajasthan', 'Rajasthan (Jaipur)'), ('Sikkim', 'Sikkim (Gangtok)'), ('Tamil Nadu', 'Tamil Nadu (Chennai)'), ('Telangana', 'Telangana (Hyderabad)'), ('Tripura', 'Tripura (Agartala)'), ('Uttarakhand', 'Uttarakhand (Dehradun)'), ('Uttar Pradesh', 'Uttar Pradesh (Lucknow)'), ('West Bengal', 'West Bengal (Kolkata)'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands (Port Blair)'), ('Chandigarh', 'Chandigarh (Chandigarh)'), ('Dadra and Nagar Haveli and Daman & Diu', 'Dadra and Nagar Haveli and Daman & Diu (Daman)'), ('The Government of NCT of Delhi', 'The Government of NCT of Delhi (Delhi)'), ('Jammu & Kashmir', 'Jammu & Kashmir (Srinagar-S*, Jammu-W*)'), ('Ladakh', 'Ladakh (Leh)'), ('Lakshadweep', 'Lakshadweep (Kavaratti)'), ('Puducherry', 'Puducherry (Puducherry)')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
